env:
  seed: 97
  gpu_id: 1
  num_workers: 12
  batch_size: 256
  # batch_size: 512
output:
  path: '/home/yiqing/data/mri_bone/result'
opt: 
  learning_rate: 5.0e-3
  min_learning_rate: 5.0e-5
  weight_decay: 1.0e-5
  gamma: 0.8
  epochs: 100
  patience: 8
  scheduler: 'cosine' # epoential
data:
  train_root: '/home/yiqing/data/mri_bone/img'
  test_root: '/home/yiqing/data/mri_bone/img'
  num_classes: 2
models:
  names:
    - "timm"
    # - "timm2"
    # - "fusion_mlp"
  timm:
    # model_name: "res2next50"
    model_name: 'resnet18'
    pretrained: True
    # pretrained: False
  # timm2:
  #   model_name: 'resnet18'
  #   pretrained: False
  # fusion_mlp:
  #   hidden_features:
  #     - 128
  #   adapt_in_features: "min"
  #   activation: "leaky_relu"
  #   dropout_prob: 0.1
  #   normalization: "layer_norm"